[package]
name = "hashid-hangul"
version = "0.1.0"
authors = ["wonjongin <wji0227@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10"
convert-base = "1.1.2"